---
title: "Wine Project"
author:
  - name: "Sergio Martinez Barajas"
  - name: "Sarah Marie Jennings"
date: today
format:
 pdf:
  execute:
   error: false
---


```{python}
#| label: python setup
#| include: false
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, KFold, cross_validate
# from sklearn.metrics import r2_score, mean_absolute_error, root_mean_squared_error, make_scorer
from plotnine import *
import matplotlib.pyplot as plt
import warnings
# import numpy as np
warnings.filterwarnings("ignore", category=RuntimeWarning)
```

```{python}
grapes = pd.read_csv("us-grape-production.csv")
temps = pd.read_csv("filtered-temp.csv")

grapes = grapes.rename(columns={
"Grapes | 00000560 || Production | 005510 || tonnes": "Grape_Production_tonnes"
})

grapes = grapes[(grapes["Year"] >= 1961) & (grapes["Year"] <= 2023)]
temps = temps[(temps["Year"] >= 1961) & (temps["Year"] <= 2023)]

merged = pd.merge(grapes, temps, on="Year")
(
ggplot(merged, aes(x="Average_Fahrenheit_Temperature", y="Grape_Production_tonnes")) +
geom_point(color="purple") +
geom_smooth(method="lm", color="black") +
labs(
title="U.S. Grape Production vs. Average Temperature (1961–2023)",
x="Average Temperature (°F)",
y="Grape Production (tonnes)"
) +
theme_minimal()
)
```


```{python}
#Correlation analysis
corr = merged["Average_Fahrenheit_Temperature"].corr(merged["Grape_Production_tonnes"])
print("Correlation:", corr)

```
what the correlation means is that there tends to be possitive correlation between average yealy temeprture and grape yield, but it's not very strong.


```{python}
#linear regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

X = merged["Average_Fahrenheit_Temperature"].values.reshape(-1, 1)
Y = merged["Grape_Production_tonnes"].values


X_train, X_test, Y_train, Y_test = train_test_split( X, Y, test_size = 0.2, shuffle = True, random_state=42)

model = LinearRegression()
model.fit(X_train, Y_train)

Y_pred = model.predict(X_test)

mae = mean_absolute_error(Y_test, Y_pred)
rmse = np.sqrt(mean_squared_error(Y_test, Y_pred))
r2 = r2_score(Y_test, Y_pred)

print("MAE: ", mae)
print("RMSE: ", rmse)
print("R^2: ", r2)

```
slope means that for every 1 F increase we get 540k tonnes increase yield but propably because temperature is average across all US, grape production is national total, there are other possible factors at work
R^2 = 0.326 means that temperture explains 32% of the variation in grape yields, which means that a whole 2/3rds of variablility is caused by something else. 


Both temp and yield increase overtime so this might make false impressions. It's not that more heat = more grapes, it could be more time = more grapes and more heat. So if we detrend the data to see if the correlation still exisits. 
```{python}
merged["Year_centered"] = merged["Year"] - merged["Year"].mean()

# detrend
from sklearn.linear_model import LinearRegression

# detrend temperature
m1 = LinearRegression().fit(merged[["Year_centered"]], merged["Average_Fahrenheit_Temperature"])
merged["Temp_detrended"] = merged["Average_Fahrenheit_Temperature"] - m1.predict(merged[["Year_centered"]])

# detrend yield
m2 = LinearRegression().fit(merged[["Year_centered"]], merged["Grape_Production_tonnes"])
merged["Yield_detrended"] = merged["Grape_Production_tonnes"] - m2.predict(merged[["Year_centered"]])

merged["Temp_detrended"].corr(merged["Yield_detrended"])
```


After detrending the data we see that correlation is bascially 0. So temp and grape yield have almost nothing to do with each other.


```{python}
####################################################
#### From here on out we're only using Cal Data ####
####################################################

grapes = pd.read_csv("Californa_Wine_Production_1980_2020.csv")
temp = pd.read_csv("California-avg-temp-1980-2021.csv")
rain = pd.read_csv("California-rain-1980-2021.csv")

# trim to overlapping years
grapes = grapes[(grapes["Year"] >= 1980) & (grapes["Year"] <= 2020)]
temp = temp[(temp["Year"] >= 1980) & (temp["Year"] <= 2020)]
rain = rain[(rain["Year"] >= 1980) & (rain["Year"] <= 2020)]

# merge
merged = grapes.merge(temp, on="Year").merge(rain, on="Year")

merged = merged.rename(columns={
    "Temp": "AvgTemp_F",
    "rain_in": "Rain_in"
})
merged[["Yield(Unit/Acre)", "AvgTemp_F", "Rain_in"]].corr()

```
What this means is that temp and percipitaion have almost no impact on yield. Although let it be known that in our lit review it did say that percipitaion almost never has an impact on yields, so that's at least 1 thing proven. Temp and rain have a negative correlation, when it rains it's colder and when hot there's less rain, but it's really weak



```{python}
county_stats = merged.groupby("County").agg({
    "Yield(Unit/Acre)": "mean",
    "HarvestedAcres": "mean",
    "AvgTemp_F": "mean",
    "Rain_in": "mean"
}).sort_values(by="HarvestedAcres", ascending=False)

print(county_stats)

```

So right here we're looking at the counties that harvest the most winegrapes. Doesn't really tell us anything


```{python}

for county in merged["County"].unique():
    sub = merged[merged["County"] == county]

    if len(sub) > 1:  # must have multiple years to plot
        plt.figure()
        plt.plot(sub["Year"], sub["HarvestedAcres"], marker="o")
        plt.title(f"Harvested Acres Over Time — {county}")
        plt.xlabel("Year")
        plt.ylabel("Harvested Acres")
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.show()
```


My theory that maybe somehow droughts and heatwaves are effecting yield is based on nothing. There is no patter or corelaion that I can see between the graphs and the dates of major droughts and heatwaves that I can see. At this point i have to a question. Is everything we've heard anecdotal? I mean to say that grape farmers are saying that it's getting harder to keep farming grapes, but so long as they keep watering their grapes, does the heat really impact them at all? I'm gonna ask my farmer friend and see what he tells me


```{python}
temps = pd.read_csv("yearly_temps.csv")

data = grapes[['Year', 'Yield(Unit/Acre)']]

df = pd.merge(grapes[['Year', 'Yield(Unit/Acre)']], temps, on='Year', how='inner')

df = df.dropna(subset=['Yield(Unit/Acre)', 'MaxTemp'])

X = df[['MaxTemp']]
Y = df['Yield(Unit/Acre)']

model = LinearRegression()
model.fit(X,Y)

y_pred = model.predict(X)

print("Slope:", model.coef_[0])
print("Intercept:", model.intercept_)
print("R^2:", r2_score(Y, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(Y, y_pred)))
print("MAE:", mean_absolute_error(Y, y_pred))
```

```{python}
import statsmodels.api as sm
from scipy.stats import pearsonr

r, p_value_corr = pearsonr(df['MaxTemp'], df['Yield(Unit/Acre)'])

print("Correlation r:", r)
print("p-value:", p_value_corr)

X = sm.add_constant(df['MaxTemp'])
Y = df['Yield(Unit/Acre)']

model = sm.OLS(Y, X).fit()

print(model.summary())
```
